blank_issues_enabled: false
contact_links:
  - name: Mrepol742 Facebook
    url: https://facebook.com/mrepol742
    about: Contact the dev on Facebook to get support ASAP.
  - name: Samiun Nafis Facebook
    url: https://facebook.com/SamiunNafis0
    about: Contact the dev on Facebook to get support ASAP.